# a=str(input("enter any sentence"))
# words=a.split()
# longest=max(words, key=len)
# print("longest word is",longest)
# print(len(longest))

# a=[2,9,3,8,4,1,7,5]
# maximum=max(a)
# minimum=min(a)
# a.remove(maximum)
# a.remove(minimum)
# max=max(a)
# min=min(a)
# print(max)
# print(min)

x="My name is Sandhra Anna Jerry"
print(type(x))
print(x[:7])
print(x[7])
print(x.casefold())
print(x.count('A'))
print(x.isdigit())
print(x.islower())
print(x.isupper())
print(x.upper())
print(x.lower())
print(x.swapcase())
print(x.center(5))